### PR TITLE
Read JSON Data for Action List

### LINKED ISSUE #17: Add Load JSON Data Support
Load JSON data for action list

### PR DESCRIPTION
**Pull request by finesaaa**
Closed #17

### CODE REVIEW

**Review by segara2410 — DISMISSED** [review]
lgtm

**Review by ichiro-its-admin — APPROVED** [review]
Looks good to me.

**Review by maroqijalil — APPROVED** [review]
good

**Review by segara2410 — CHANGES_REQUESTED** [review]
Please add a new line at the end of every file.

**Pull request merged**
